# -*- coding: utf-8 -*-
"""tste_vento.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3g2Nchp9WGgMIP4LT1j_91oWmSuFR2a
"""

import numpy as np
import pandas as pd
pd.plotting.register_matplotlib_converters()
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['dados.csv'])) #salvando o dataframe na variavel df
df = df.drop(df.columns[df.columns.str.contains('unnamed',case = False)], axis = 1) #Eliminando coluna em

df['TEM_INS'].fillna(df['TEM_INS'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da temperatura
df['UMD_INS'].fillna(df['UMD_INS'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da umidade
df['VEN_VEL'].fillna(df['VEN_VEL'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da velocidade do vento

df

vdate = pd.date_range('2020-10-01',end='2021-10-01', freq='H')

vetor=df['VEN_VEL'].values

x=pd.DataFrame(vdate)

w=x.drop(8760)

w.columns=['DATA']

w.insert(loc=1, column='VEL_VENTO',value=vetor)

type(w)

w.columns=['ds','y']

w



w.dtypes

from fbprophet import Prophet

modelo=Prophet()
modelo.fit(w)

data_futuro = pd.date_range('2022-01-19',end='2022-01-20', freq='H')

data_futuro

dtf = pd.DataFrame(data_futuro)

dtf.columns = ['ds']

dtf = dtf.drop(24)

dtf

previsao = modelo.predict(dtf)

previsao

t=previsao[['ds','yhat']]

type(t)



t.columns=['data ','vel_vent']
t