# -*- coding: utf-8 -*-
"""Temp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rb_zQyW3rNocCKxe9y9Auy5pqIpO64X
"""

import numpy as np
import pandas as pd
pd.plotting.register_matplotlib_converters()
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['dados.csv'])) #salvando o dataframe na variavel df
df = df.drop(df.columns[df.columns.str.contains('unnamed',case = False)], axis = 1) #Eliminando coluna em

df['TEM_INS'].fillna(df['TEM_INS'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da temperatura
df['UMD_INS'].fillna(df['UMD_INS'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da umidade
df['VEN_VEL'].fillna(df['VEN_VEL'].mean(),inplace = True)#Cada dado faltante foi substituído pela média da velocidade do vento

vdate = pd.date_range('2020-10-01',end='2021-10-01', freq='H')

vetor=df['TEM_INS'].values

x=pd.DataFrame(vdate)

w=x.drop(8760)

w.columns=['DATA']

w.insert(loc=1, column='TEM_INST',value=vetor)

w.columns=['ds','y']

from fbprophet import Prophet

modelo=Prophet()
modelo.fit(w)

data_futuro = pd.date_range('2022-01-19',end='2022-01-20', freq='H')

data_futuro



dtf = pd.DataFrame(data_futuro)

dtf.columns = ['ds']

previsao = modelo.predict(dtf)

previsao

t=previsao[['ds','yhat']]

t

t=t.drop(24)

t.columns=['data ','Temp_inst']

